Play travis
Otus-DevOps-2021-05/zolo20_infra pull request #3
Opened 2021-07-17 17:22 UTC by zolo20

2021-07-18 13:26 UTC, mrgreyves requested changes
Здравствуйте!) Это жд нужно выполнять в своем репозитории созданном специально для курса. ДЗ нужно перенести в него, дз возвращаю на доработку =)

2021-07-18 13:41 UTC, zolo20 commented
Здравствуйте!
Я не могу коммитить туда, пишет permission denied
откройте доступа, тогда уж)

2021-07-18 14:57 UTC, mrgreyves commented
Вам нужно было принять приглашения которые высылались на почту =) Добавил вам доступ =)

2021-07-18 14:58 UTC, mrgreyves commented
Приглашения снова отправлены на почту, не забудьте их принять =)

2021-07-28 05:14 UTC, zolo20 commented
Я за пулил
Не могли бы проверить

2021-08-04 15:12 UTC, closed without merging