Pay travis
Otus-DevOps-2021-05/zolo20_infra pull request #6
Opened 2021-08-04 15:24 UTC by zolo20

Pay travis

2021-08-04 18:42 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комметарий к файлу, дз возвращаю на доработку.

2021-08-04 18:42 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Вот тут ошибочка =)

2021-08-04 20:52 UTC, zolo20 commented
Здравствуйте!
Исправил, спасибо.

2021-08-06 13:36 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь апрув!=)

2021-08-06 15:43 UTC, merged